# Generated by Django 4.0.4 on 2022-05-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0002_rename_edad_curso_codigo_remove_curso_apellido_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservas',
            new_name='Reserva',
        ),
    ]
