# Generated by Django 4.0.4 on 2022-05-29 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0006_student_delete_estudiante'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Course',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='codigo',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='duracion',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='nombre',
            new_name='name',
        ),
    ]
